create table if not exists public.sales(id bigint generated by default as identity primary key,date date not null,product text not null,quantity integer not null,sales numeric not null,profit numeric not null);
create table if not exists public.purchases(id bigint generated by default as identity primary key,date date not null,item text not null,amount numeric not null);
alter table public.sales enable row level security;
alter table public.purchases enable row level security;
create policy "personal sales" on public.sales for all to anon using(true) with check(true);
create policy "personal purchases" on public.purchases for all to anon using(true) with check(true);